document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:3,');
document.writeln('pageName:"Introduction",');
document.writeln('mapId:"datasheet2",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:0,');
document.writeln('stageH:0,');
document.writeln('mapWidth:0,');
document.writeln('mapHeight:0,');
document.writeln('mapAreaScale:NaN,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:true,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[],');
document.writeln('markerStyleTable:[],');
document.writeln('pageId:"30104",');
document.writeln('mapFileName:"0100_01_0000.jpg",');
document.writeln('mapInsetFileName:"_0100_01_0000.jpg",');
document.writeln('mapSwfName:"0050_03_0000.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"NaN",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'datasheet2\',\'Introduction\',\'<div class="nlmText"> <div class="nlmTextBold" style="margin-top: 8px;">Between 1997 and 2011, NLM launched a series of innovative programs in Africa based on NIH\\\'s engagement in the Multilateral Initiative on Malaria and NLM\\\'s emerging and new priorities for serving global health. This presentation is an opportunity to:</div> <ul style="margin: 6px 0px;">     <li class="nlmListItem">hear the voices of the people involved</li>     <li class="nlmListItem">see an overview of these initiatives</li>     <li class="nlmListItem">view their locations on the African continent</li> </ul> <div class="nlmTextBold" style="margin: 8px 0px 12px; font-style: italic;">Choose a topic from the menu above to explore:</div> <table cellspacing="0" cellpadding="2" border="1" class="nlmIntroTable">     <tbody>         <tr>             <td class="nlmTextBold" style="vertical-align: top; width: 195px;">What do you think of when you think of Africa?</td>             <td style="vertical-align: top;">Explore some of the images we have in mind about Africa.</td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Guiding Principles</td>             <td style="vertical-align: top;">The overarching goals for all of our work in Africa</td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Engaging communities in Africa</td>             <td style="vertical-align: top;">See one program across several countries. Each of the colored circles represents a major focus:             <ul>                 <li class="nlmGreen nlmTextBold">Developing a Culture of Research and Community Involvement: African Medical Students</li>                 <li class="nlmPurple nlmTextBold">Connecting African Malaria Researchers: Multilateral Initiative on Malaria Communications Network (MIMCom)</li>                 <li class="nlmBlue nlmTextBold">Strengthening African Medical Journals: African Journal Partnership Project (AJPP)</li>                 <li class="nlmOrange nlmTextBold">Empowering African Medical Librarians:  NLM Associates Program and the Network of                 African Medical Librarians (NAML)</li>             </ul>             Click on these colored circles to learn more, including text, photos, and video.</td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Project Locations</td>             <td style="vertical-align: top;">Discover which NLM programs have been active in a particular country. Click the shaded countries on the map of Africa to view detailed maps of active programs.             <p><br />             </p>             <p style="margin-bottom: 0px;">Click the colored dots on the detailed maps for more information on specific programs.</p>             </td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Videos</td>             <td style="vertical-align: top;">The list of videos included in this presentation.</td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Links</td>             <td style="vertical-align: top;">Links to web sites and other sources of information</td>         </tr>         <tr>             <td class="nlmTextBold" style="vertical-align: top;">Credits</td>             <td style="vertical-align: top;">View some of the many people who have contributed to these projects, truly a collaborative venture.</td>         </tr>     </tbody> </table> </div>\',\'<iframe width="420" height="315" src="http://www.youtube.com/embed/BIBoxnUqv6M" frameborder="0" allowfullscreen></iframe>\',\'gallery2\',\'datasheet6\',\'map4\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'students\',\'videos\',\'datasheet5\',\'creditsvideo\'],');
document.writeln('pageTable:[\'0,3\',\'4,4\',\'5,15\',\'6,6\',\'7,1\',\'8,7\',\'9,8\',\'10,9\',\'11,10\',\'12,13\',\'13,14\',\'14,16\'],');
document.writeln('slideTable:[\'610390,3,0,1,2,-1,420,315,1,3,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'other\',\'datasheet2\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:610390,');
document.writeln('accountId:300559,');
document.writeln('layout:"VTTII",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:437,');
document.writeln('mediaAreaH:569,');
document.writeln('textAreaW:805,');
document.writeln('textAreaH:569,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:10,');
document.writeln('layoutMarginRight:10,');
document.writeln('layoutMarginBottom:10,');
document.writeln('layoutMarginLeft:10,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)" class="current">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('    <div id="maTextArea" style="margin:0px 8px 10px 0px;">');
document.writeln('      <div id="maHotspotTitle">');
document.writeln('      </div>');
document.writeln('      <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('    </div>');
document.writeln('    <div id="maAbsBlock" style="top:10px; left:823px; width:437px; height:569px;">');
document.writeln('      <div id="maHotspotMediaArea" style="margin-bottom:0px;"></div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
