document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:6,');
document.writeln('pageName:"Engaging communities in Africa",');
document.writeln('mapId:"map4",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:471,');
document.writeln('stageH:589,');
document.writeln('mapWidth:471,');
document.writeln('mapHeight:589,');
document.writeln('mapAreaScale:1,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:false,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"0023_03_0020.gif",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[\'611637,2,193292,0,0,0.490299823633157,0.202816901408451,1,101,101,0,0,0,0,0,0,0,0,0,0,64,1,0,1,0,1,0,1,0,1,0\',\'611619,2,193292,0,0,0.777777777777778,0.423943661971831,1,101,101,0,0,0,0,0,0,0,0,0,0,64,1,0,1,0,1,0,1,0,1,0\',\'611638,2,193292,0,0,0.212903225806452,0.430927835051546,1,101,101,0,0,0,0,0,0,0,0,0,0,64,1,0,1,0,1,0,1,0,1,0\',\'611639,2,193292,0,0,0.495590828924162,0.673239436619718,1,101,101,0,0,0,0,0,0,0,0,0,0,64,1,0,1,0,1,0,1,0,1,0\'],');
document.writeln('markerStyleTable:[\'193292,8,#ffffff,#999999,#666666,#ffff00,0,0,0,80,1,1\'],');
document.writeln('pageId:"30107",');
document.writeln('mapFileName:"0107_01_0085.jpg",');
document.writeln('mapInsetFileName:"_0107_01_0085.jpg",');
document.writeln('mapSwfName:"0050_06_0370.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"100",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'53,53,50\',\'\',\'datasheet2\',\'gallery2\',\'datasheet6\',\'map4\',\'0189_01_0017.jpg\',\'H5\',\'_AJPP group photo 2011\',\'H1\',\'Connecting African Malaria Researchers: MIMCom\',\'<div class="nlmText"> <div style="font-size: 16px;" class="nlmTitle nlmPurple">Connecting African Malaria Researchers: MIMCom</div> <p>Initially targeting one area of opportunity in 1997, NLM played a critical role with NIH in the Multilateral Initiative on Malaria (MIM), providing enhanced access to the Internet and to medical literature for malaria research sites in Africa where there was little or no access. Eventually comprising 27 malaria research sites and units within institutions in 14 countries, MIMCom was sustained by the research funders and partners at each site. </p> <span style="font-size: 14px;"><strong><a href="javascript:maClient.goToPage(\\\'page9.htm\\\',null);">Click to see map -- Connecting African Malaria Researchers: MIMCom map</strong></span></a><br /> <br /> <p> MIMCom facilitated malaria research in: epidemiology, antimalarial drug resistance, pathogenesis and immunology, entomology and vector studies, natural products and drug development, and health systems and social sciences.</p> <img src=":0197_01_0017.jpg"/><br /> <br /> <p> The MIMCom network made a positive contribution to the performance of malaria researchers and support staff at the sites. Connectivity improved e-mail exchange and the ability of researchers in Africa to reach out to colleagues and funders around the world, access published literature and databases, collaborate on scientific papers, and develop and submit research proposals. These tools enabled African scientists to communicate, carry out research, publish, and feel part of the international scientific community.</p> <p> In the first video, Dr. David Afori-Adjei, Rector, Ghana College of Physicians and Surgeons, describes the accomplishments of MIMCom and the differences it made for the malaria research community in Africa. In the video below, Dr. Andrew Githeko of the Kenyan Medical Research Institute (KEMRI) talks about his work before and after the installation of satellite communications in July 1999.</p> <iframe src="http://www.youtube.com/embed/UxJy3K-oqIQ" width="560" height="315" frameBorder="0" scrolling="no" ></iframe></div>\',\'<iframe width="560" height="315" src="http://www.youtube.com/embed/1Z6ahOhbNzM" frameborder="0" allowfullscreen></iframe>\',\'students\',\'Developing a Culture of Research and Community Involvement: African Medical Students\',\'<div class="nlmText"> <div style="font-size: 16px;" class="nlmTitle nlmGreen"><span style="font-size: 10px;"><em>In the video above, Ugandan medical students discuss: Field Testing Challenges and Rewards; Tackling Community Beliefs; The Value of Visual Imagery; Empowering Communities to Help Themselves; Agents of Change.<br /> </em></span><br /> Developing a Culture of Research and Community Involvement: African Medical Students</div> <p> A large part of NLM\\\'s focus in Africa is working with students (they are the future!), so training, mentoring, and encouraging their work and ideas is very important. </p> <p> This effort began as an "information intervention" in Mifumi village in Eastern Uganda. The village and its Health Center became part of the Community Based Education and Service Program (COBES) of the medical school at Makerere University in Kampala, Uganda. <br /> <br /> <strong style="font-size: 14px;"><a href="javascript:maClient.goToPage(\\\'page10.htm\\\',null);">Click to see map -- Developing a Culture of Research and Community Involvement: African Medical Students</a></strong></p> <p> NLM worked with the students and the nurse sister at the health center to carry out a baseline survey on knowledge about malaria; implement the MedlinePlus malaria tutorial in several media and local languages; and, in collaboration with Ugandan health informatics experts, conduct a study in actual use of bednets, employing a digital pen application for collecting data. </p> <p> This last project concluded with a community meeting in which the students presented their research findings back to the village. Over 150 people came and stayed for two hours.</p> <p> This work in Mifumi village has inspired expansion into other tutorials designed to help both health professionals and communities deal with local health problems, including mental health in war-torn Northern Uganda, tuberculosis, diarrhea, and Burkitt\\\'s Lymphoma, the latter in collaboration with the National Cancer Institute.</p> <br /> </div>\',\'<iframe width="560" height="315" src="http://www.youtube.com/embed/DZ_yZpb-mzc" frameborder="0" allowfullscreen></iframe>\',\'H3\',\'Empowering African Medical Librarians:  NLM Associate Fellows and Network of African Medical Librarians\',\'<div class="nlmText"> <div style="font-size: 16px;" class="nlmTitle nlmOrange">Empowering African Medical Librarians:  NLM Associate Fellows and Network of African Medical Librarians</div> <p>In 2001, NLM invited the first African medical librarian to be part of NLM&rsquo;s year long, primarily domestic, Associate Fellows Program. Since then, six librarians from the African continent have participated. These librarians and others from a total of seven academic institutions in Kenya, Mali, Mozambique, Nigeria, Uganda, Zambia and Zimbabwe have now formed the Network of African Medical Librarians, an independent consortium with a secretariat at Kenyatta University in Kenya. </p> <p>The Network&rsquo;s vision is to strengthen health sciences education, research and outreach for better health outcomes in Africa. Their mission is to expand the frontiers of knowledge through the training of, and outreach to African librarians, the academic community, health care professionals, health policy makers in finding, organizing and using of health information.</p> <p> The Network has been active in improving electronic access to research and health care information for researchers, students, health care workers and policy makers in Africa. To this end, the Network, with support from NLM, has developed a training manual titled Finding, Organising and Using Health Information which is available in print and electronic formats.</p> <span style="font-size: 14px;"><strong><a href="javascript:maClient.goToPage(\\\'page7.htm\\\',null);">Click to see map -- African Medical Librarians</a></strong></span><br /> <br /> <iframe src="http://www.youtube.com/embed/QklRHWwK4gU" width="560" height="315" frameBorder="0" scrolling="no" ></iframe></div>\',\'<iframe width="560" height="315" src="http://www.youtube.com/embed/ZhMeFImWvrE" frameborder="0" allowfullscreen></iframe>\',\'0199_01_0017.jpg\',\'H7\',\'Mimcom Partnerships\',\'0197_01_0017.jpg\',\'mimtdr\',\'H4\',\'Strengthening African Medical Journals: African Journal Partnership Project\',\'<div class="nlmText"> <div style="font-size: 16px;" class="nlmTitle nlmBlue">Strengthening African Medical Journals: African Journal Partnership Project</div> <p>Peer-reviewed journals are a vital source of information exchange. However, journals in developing regions often lack the necessary resources to publish in a timely manner. </p> <p> To address these needs, the African Journal Partnership Project (AJPP) was created in 2003 as a collaborative effort among NLM, the Fogarty International Center, the National Institute of Environmental Health Sciences, and 9 journals from the US, UK, and Africa.</p> <p> The AJPP partners African health and medical journals with leading journals published in the United States and the United Kingdom. The goal of the program is to strengthen the African health and medical journals so that they can be accepted into MEDLINE, resulting in African health and medical research being available to the world. The premise behind the project is that valuable research is being carried out in endemic countries but is not often available to a wider international audience.<br /> <br /> <strong style="font-size: 14px;"><a href="javascript:maClient.goToPage(\\\'page8.htm\\\',null);">Click to see map -- African Journal Partnership Project</a></strong></p> <p class="nlmTextBold" style="margin-bottom: 3px;">Members:</p> <ul style="margin: 5px 0px;">     <li>Ethiopia : Ethiopian Journal of Health Sciences partnered with Annals of Internal Medicine*</li>     <li>Ghana : Ghana Medical Journal partnered with The Lancet*</li>     <li>Malawi : Malawi Medical Journal partnered with the Journal of the American Medical Association*</li>     <li>Mali : Mali Medical Journal partnered with &nbsp;Environmental Health Perspectives*</li>     <li>Uganda : African Health Sciences partnered with the British Medical Journal*</li>     <li>Zambia : Medical Journal of Zambia partnered with the New England Journal of Medicine</li> </ul> <p style="font-size: 10px;">* Indicates acceptance into MEDLINE</p> <p>The Council of Science Editors (CSE) provides a secretariat for AJPP.</p> <img width=\\\'675px\\\' src=":0189_01_0017.jpg"/> </div>\',\'<iframe width="560" height="315" src="http://www.youtube.com/embed/sFFfqMOVt0g" frameborder="0" allowfullscreen></iframe>\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'videos\',\'datasheet5\',\'creditsvideo\'],');
document.writeln('pageTable:[\'2,3\',\'3,4\',\'4,15\',\'5,6\',\'30,1\',\'31,7\',\'32,8\',\'33,9\',\'13,10\',\'34,13\',\'35,14\',\'36,16\'],');
document.writeln('slideTable:[\'668989,6,7,8,1,6,722,481,0,-1,0,0,0,-1,-1,-1\',\'611619,6,9,10,11,-1,560,315,1,12,0,0,0,-1,-1,-1\',\'611637,6,13,14,15,-1,560,315,1,16,0,0,0,-1,-1,-1\',\'611638,6,17,18,19,-1,560,315,1,20,0,0,0,-1,-1,-1\',\'680224,6,22,23,1,21,642,481,0,-1,0,0,0,-1,-1,-1\',\'671383,6,25,25,1,24,448,271,0,-1,0,0,0,-1,-1,-1\',\'611639,6,26,27,28,-1,560,315,1,29,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'other\',\'H5\',\'H1\',\'students\',\'H3\',\'H7\',\'mimtdr\',\'H4\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:611637,');
document.writeln('accountId:300559,');
document.writeln('layout:"VMMIT",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:791,');
document.writeln('mediaAreaH:300,');
document.writeln('textAreaW:791,');
document.writeln('textAreaH:281,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:0,');
document.writeln('layoutMarginRight:0,');
document.writeln('layoutMarginBottom:0,');
document.writeln('layoutMarginLeft:0,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)" class="current">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('<div id="maMap" style="position:relative;width:471px;height:589px;overflow:hidden;margin-bottom:0px;"><script type="text/javascript">');
document.writeln('var mapViewer=new maClient.MapViewer();');
document.writeln('</script></div>');
document.writeln('<div id="maAbsBlock" style="top:0px; left:479px; width:791px;">');
document.writeln('      <div id="maHotspotMediaArea" style="margin-bottom:8px;"></div>');
document.writeln('      <div id="maTextArea" style="margin:8px 0px 0px 0px;">');
document.writeln('        <div id="maHotspotTitle">');
document.writeln('        </div>');
document.writeln('        <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
