document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:10,');
document.writeln('pageName:"Students",');
document.writeln('mapId:"students",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:545,');
document.writeln('stageH:589,');
document.writeln('mapWidth:545,');
document.writeln('mapHeight:588,');
document.writeln('mapAreaScale:1,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:false,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"0023_03_0020.gif",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[\'652713,2,164042,0,0,0.497247706422018,0.578231292517007,2,9,9,0,0,0,0,0,0,0,0,0,0,64,2,0,1,0,1,0,1,0,1,0\',\'652717,4,32285,0,0,0.831192660550459,0.0646258503401361,2,160,47,0,0,0,0,0,0,0,0,0,0,1024,1,1,4,0,1,0,1,0,2,3\',\'652712,2,164042,0,0,0.675229357798165,0.534013605442177,2,9,9,0,0,0,0,0,0,0,0,0,0,64,5,0,1,0,1,0,1,0,1,0\',\'652714,2,164042,0,0,0.574311926605505,0.399659863945578,2,9,9,0,0,0,0,0,0,0,0,0,0,64,6,0,1,0,1,0,1,0,1,0\',\'652716,2,164042,0,0,0.592660550458716,0.408163265306122,2,9,9,0,0,0,0,0,0,0,0,0,0,64,7,0,1,0,1,0,1,0,1,0\',\'659579,2,164042,0,0,0.478899082568807,0.583333333333333,2,9,9,0,0,0,0,0,0,0,0,0,0,64,8,0,1,0,1,0,1,0,1,0\',\'688617,2,164042,0,0,0.488073394495413,0.564625850340136,2,9,9,0,0,0,0,0,0,0,0,0,0,64,9,0,1,0,1,0,1,0,1,0\',\'652711,2,164042,0,0,0.662385321100917,0.523809523809524,2,9,9,0,0,0,0,0,0,0,0,0,0,64,10,0,1,0,1,0,1,0,1,0\',\'652715,2,164042,0,0,0.645871559633028,0.534013605442177,2,9,9,0,0,0,0,0,0,0,0,0,0,64,11,0,1,0,1,0,1,0,1,0\'],');
document.writeln('markerStyleTable:[\'164042,1,#ffffff,#000000,#00ff00,#000000,100,100,100,100,1,1\',\'32285,2,#aa0000,#666666,#a40000,#666666,100,100,100,100,1,12\'],');
document.writeln('pageId:"33328",');
document.writeln('mapFileName:"0139_01_0068.jpg",');
document.writeln('mapInsetFileName:"_0139_01_0068.jpg",');
document.writeln('mapSwfName:"0050_10_0305.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"100",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'0,0,8,8\',\'\',\'Makerere University, Kampala\',\'0,0,159,46\',\'page6.htm\',\'eHMIS: Tororo Hospital, Tororo, Uganda\',\'Burkitt\\\'s Lymphoma Tutorial: Gulu, Uganda\',\'Mental Health Tutorial: Gulu, Uganda\',\'Tuberculosis Tutorial: Mulago Hospital, Kampala, Uganda\',\'Diarrhea Tutorial: Kampala, Uganda\',\'Bednet/Digital Pen Study: Mifumi Village, Uganda\',\'Malaria Tutorial: Mifumi Village, Uganda\',\'shadow\',\'datasheet2\',\'gallery2\',\'datasheet6\',\'map4\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'students\',\'0211_01_0007.jpg\',\'bednetstudentsnight\',\'bednet students night\',\'9\',\'Bednet/Digital Pen Study, Mifumi Village, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Bednet/Digital Pen Study, Mifumi Village, Uganda</div> <table>     <tbody>         <tr>             <td>In 2010, NLM supported the transfer of a digital pen application, developed as part of disaster preparedness at NLM, to serve an observational study on actual bednet use in an African village.  The study was carried out in Mifumi village in Eastern Uganda by a team of Makerere University medical students and Mifumi Health Center.  The students were mentored by two technical teams, one at NLM and one in Uganda, as well as the nurse sister of the health center and the Mifumi village community. The students&rsquo; quest was to see whether the 300 bednets distributed in 2006 were actually being used to prevent malaria and to evaluate how digital pen technology could support efficient and timely collection, collation, and presentation of the research data regarding use of the nets.</td>             <td style="padding-right: 8px;"><img src=":0211_01_0007.jpg"/><br />             <p style="font-size: 11px;">Nighttime data collection by a medical student from Makerere University</p>             </td>         </tr>     </tbody> </table> <p> From this small study, it is evident that households endeavor to use mosquito nets and to clear their surroundings of bushes and stagnant water where mosquitoes breed. It is also apparent that a great number of households hang up their nets appropriately and that a majority of nets were in active use. Malaria prevalence remains high, which could be attributed to the fact that many nets were damaged, some even beyond repair, as well as the general tendency of villagers to spread the nets after dusk.  It was also observed that in a number of households, a single torn net was shared among two to three children under five.  </p> <p> However, the trend in morbidity and mortality in the village is downward since this collaborative information intervention which began three years ago.  A community meeting in the village to present results of the survey to the people in village was attended by over 150 people and lasted for two hours.  The people very much appreciated that the research was being presented to them, and that their ideas were being considered.</p> <br /> <iframe src="http://www.youtube.com/embed/JLq8u78p0Ro" width="480" height="360" frameBorder="0" scrolling="no" ></iframe> </div>\',\'0213_01_0008.jpg\',\'burkitts\',\'0214_01_0007.jpg\',\'burkitts devil\',\'13\',\'Burkitt\\\'s Lymphoma Tutorial, Gulu, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Burkitt\\\'s Lymphoma Tutorial, Gulu, Uganda</div> <table>     <tbody>         <tr>             <td style="vertical-align: top;">In conjunction with the National Cancer Institute\\\'s study on the Epidemiology of Burkitt\\\'s Lymphoma in East African Children and Minors (EMBLEM), NLM has worked with Lacor Hospital, the Uganda Cancer Institute in Mulago, and medical students to develop a tutorial about Burkitt\\\'s Lymphoma to increase community awareness of the disease.  To create this tutorial, NLM brought together artists and students with clinicians and researchers, resulting in a lively dialog and useful educational materials.  The latter included a Burkitt\\\'s Lymphoma video tutorial as well as a community awareness campaign, including posters on "why people in our community seek treatment late" and a pictorial informed consent. </td>             <td style="padding-right: 8px;"><img src=":0213_01_0008.jpg"/></td>         </tr>     </tbody> </table> <br /> <img src=":0214_01_0007.jpg"/></div>\',\'0216_01_0008.jpg\',\'burkitts2\',\'0207_01_0016.jpg\',\'diarrhea luganda\',\'0210_01_0009.jpg\',\'diarrhea2\',\'diarrhea luganda 2\',\'0198_01_0022.jpg\',\'ehmis\',\'0212_01_0008.jpg\',\'ehmis1\',\'ehmis 1\',\'7\',\'Electronic Health Management Information System (eHMIS), Tororo Hospital, Tororo, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Electronic Health Management Information System (eHMIS), Tororo Hospital, Tororo, Uganda, and Mifumi Health Center, Uganda</div> <img src=":0212_01_0008.jpg"/> <p>The eHMIS (Electronic Health Management Information System) research project was piloted in Tororo District Hospital in Eastern Uganda in 2004 by Dr. Simon Ndira within the context of his PhD research under the Institute of Medical Biometry and Medical Informatics, Heidelberg University, Germany.</p> <p> The project aimed at assessing the effect of electronic health records on data quality including timeliness, availability and accuracy of reports, as well as staff satisfaction with the system in place. The resulting eHMIS application captures patient data from encounter to discharge with an uplink to routine report and is the first such system in Uganda.</p> <p> NLM supported the roll out of the eHMIS at Tororo District Hospital as well as at Mifumi Health Center in a village 35 kilometers away.  The eHMIS project has also been supported by EPOS Health Management in Germany, MIFUMI Project in Tororo,  and the Department of Medical Informatics at Heidelberg University.  Additional hospital implementations are planned.</p> <br /> <img src=":0198_01_0022.jpg"/> </div>\',\'0208_01_0007.jpg\',\'Makere\',\'Makere University\',\'H24\',\'Makerere University College of Health Sciences, Kampala, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Makerere University College of Health Sciences, Kampala, Uganda</div> <table>     <tbody>         <tr>             <td>NLM has worked with Makerere University College of Health Sciences as a flagship partner in Uganda. In collaboration with the Faculty of Medicine, NLM initiated the MedlinePlus African Tutorials project.<br />             <br />             <p>             First, NLM engaged an advisory group of African scientists and physicians from across the continent to identify top health concerns as a focus for the tutorials. The first tutorial on malaria was created in collaboration with the Faculty of Medicine and a team of Ugandan doctors, medical students, artists, and translators. Faculty members worked with an artistic team to create locally meaningful text and illustrations for the tutorials. The malaria tutorial was then field tested in villages by medical students and translated from English into five local languages - Japadhola, Luganda, Luo, Runyankole and Swahili.</p>             </td>             <td style="padding-right: 8px;"><img src=":0208_01_0007.jpg"/></td>         </tr>     </tbody> </table> Medical students, health workers and staffs of clinics use the tutorials in both electronic and hard copy formats to educate the general public as part of the Faculty of Medicine\\\'s Community Based Education and Service (COBES) program.  COBES requires each medical student to spend one to two months a year working at a community health site such as the Health Centre in Mifumi Village. <p></p> <p> Mission of College of Health Sciences: "We are dedicated to improving the health of the people of Uganda and beyond and promoting health equity by providing quality education, research and health services. We achieve this by enhancing capacity and participation of stakeholders; strengthening systems and partnerships; and harnessing the power of new sciences and technology so as to build and sustain excellence and relevance."</p> </div>\',\'0175_01_0029.jpg\',\'malariapng\',\'MedlinePlus Diarrhea Tutorial\',\'MedlinePlus Diarrhea Tutorial, Kampala, Uganda\',\'<div class="nlmText"> <div class="nlmTitle nlmGreen" style="font-size: 18px;">Developing a Culture of Research and Community Involvement:<br /> MedlinePlus Diarrhea Tutorial, Kampala, Uganda</div> <p>Diarrhea remains one of the leading causes of childhood morbidity and mortality in the developing world. This tutorial includes information about how diarrhea is contracted, the importance of treatment and techniques for prevention.  It is a collaboration between the U.S. National Library of Medicine and Makerere University Faculty of Medicine, and was produced in six languages: English, Japadhola, Luganda, Luo, Runyankole, and Swahili.</p> <img src=":0210_01_0009.jpg"/> <br /> <br /> <img src=":0207_01_0016.jpg"/> </div>\',\'11\',\'MedlinePlus Malaria Tutorial,  Mifumi Village, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> MedlinePlus Malaria Tutorial, Mifumi Village, Uganda</div> <p>NLM created the first MedlinePlus African tutorials on malaria and diarrhea in collaboration with the Faculty of Medicine at Makerere University and a team of Ugandan medical students, artists, and translators. Faculty members worked with the team to create locally meaningful text and illustrations for the tutorials. </p> <p> The malaria tutorials were field tested in Mifumi village in Eastern Uganda by COBES (Community Based Education and Service) medical students from Makerere University.  NLM  worked with the students to carry out a baseline survey on knowledge about malaria and to implement the MedlinePlus malaria tutorial as well in several media and local languages (Japadhola, Luganda, Luo, Runyankole, and Swahili, as well as English).  Medical students, health workers and staffs of clinics use the tutorials in both electronic and hard copy formats to educate the general public.  After initial testing, the COBES program distributed the tutorials to all students carrying out field work in rural areas. </p> <br /> <iframe src="http://www.youtube.com/embed/BKCRoMIYokI" width="480" height="360" frameBorder="0" scrolling="no" ></iframe><br /> <br /> <img src=":0175_01_0029.jpg"/><br /> </div>\',\'<iframe width="560" height="315" src="http://www.youtube.com/embed/3O2lpnQbgv4" frameborder="0" allowfullscreen></iframe>\',\'12\',\'Mental Health Tutorial, Gulu, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Mental Health Tutorial, Gulu, Uganda</div> <table>     <tbody>         <tr>             <td style="vertical-align: top;">As a result of 20 years of war and massive displacement of people, Northern Uganda has been plagued by serious issues of mental health.  Working with NLM, the Gulu Medical School created a tutorial on mental health to improve recognition, detection, diagnosis and care for individuals with depression, or other individuals at risk of developing depression. &nbsp;Artwork for the tutorial was created by children from the Northern Uganda region and curated by Ronnie Ogwang.  &nbsp;The tutorial was used as a &ldquo;next step&rdquo; intervention to follow a mental health survey carried out in the district by medical students. The mental health problems emerging from the analysis of the survey results formed the basis for the text of the tutorial.  Tutorials were distributed to a variety of organizations, including a teaching college and non-governmental organizations, the military, a prison and schools.</td>             <td style="padding-right: 8px;"><img src=":0218_01_0004.jpg"/></td>         </tr>     </tbody> </table> <img src=":0188_01_0021.jpg"/> </div>\',\'0218_01_0004.jpg\',\'mentalhealth1\',\'0188_01_0021.jpg\',\'H11\',\'monster\',\'H8\',\'Return\',\'0209_01_0009.jpg\',\'tbflyer\',\'tb flyer\',\'0217_01_0006.jpg\',\'poster\',\'tb poster\',\'tb\',\'Tuberculosis Tutorial, Mulago Hospital, Kampala, Uganda\',\'<div class="nlmText"> <div style="font-size: 18px;" class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement:<br /> Tuberculosis Tutorial, Mulago Hospital, Kampala, Uganda</div> <p> This was a collaboration between artists Ronnie Ogwang and Charles Isabirye and Makerere University medical students, and was produced in English and Swahili.  This tutorial and the others on malaria, diarrhea, depression, and Burkitt\\\'s lymphoma are being made available in disk format for students working in rural areas.</p> <img src=":0209_01_0009.jpg"/><br /> <br /> <img src=":0217_01_0006.jpg"/></div>\',\'Uganda\',\'_Uganda\',\'<span style="font-size: 18px; color: #00b050;"><strong><span style="color: #000000;">Uganda</span><br /> Developing a Culture of Research and Community Involvement: <span style="font-size: 18px;">African Medical Students</span></strong></span><span style="font-size: 16px;"><strong></strong></span>\',\'videos\',\'datasheet5\',\'creditsvideo\'],');
document.writeln('pageTable:[\'13,3\',\'14,4\',\'15,15\',\'16,6\',\'17,1\',\'18,7\',\'19,8\',\'20,9\',\'21,10\',\'87,13\',\'88,14\',\'89,16\'],');
document.writeln('slideTable:[\'701562,10,23,24,1,22,259,195,0,-1,0,0,0,-1,-1,-1\',\'652711,10,25,26,27,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'701670,10,29,29,1,28,394,481,0,-1,0,0,0,-1,-1,-1\',\'688656,10,31,31,1,30,353,481,0,-1,0,0,0,-1,-1,-1\',\'652714,10,32,33,34,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'701671,10,36,36,1,35,353,481,0,-1,0,0,0,-1,-1,-1\',\'689180,10,38,38,1,37,690,477,0,-1,0,0,0,-1,-1,-1\',\'701561,10,40,41,1,39,690,477,0,-1,0,0,0,-1,-1,-1\',\'671390,10,43,43,1,42,641,481,0,-1,0,0,0,-1,-1,-1\',\'701669,10,45,46,1,44,641,481,0,-1,0,0,0,-1,-1,-1\',\'652712,10,47,48,49,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'701470,10,51,52,1,50,259,194,0,-1,0,0,0,-1,-1,-1\',\'652713,10,53,54,55,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'656936,10,57,57,1,56,690,479,0,-1,0,0,0,-1,-1,-1\',\'688617,10,58,59,60,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'652715,10,61,62,63,-1,560,315,1,64,0,0,0,-1,-1,-1\',\'652716,10,65,66,67,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'701676,10,69,69,1,68,394,356,0,-1,0,0,0,-1,-1,-1\',\'671147,10,71,72,1,70,611,481,0,-1,0,0,0,-1,-1,-1\',\'652717,10,73,74,1,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'701559,10,76,77,1,75,682,481,0,-1,0,0,0,-1,-1,-1\',\'688616,10,79,80,1,78,340,481,0,-1,0,0,0,-1,-1,-1\',\'659579,10,81,82,83,1,0,0,0,-1,0,0,0,-1,-1,-1\',\'652679,10,84,85,86,1,0,0,0,-1,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'med\',\'9\',\'13\',\'7\',\'11\',\'12\'],[\'cou\',\'Uganda\'],[\'other\',\'bednetstudentsnight\',\'burkitts\',\'burkitts devil\',\'burkitts2\',\'diarrhea luganda\',\'diarrhea2\',\'ehmis\',\'ehmis1\',\'Makere\',\'H24\',\'malariapng\',\'MedlinePlus Diarrhea Tutorial\',\'mentalhealth1\',\'H11\',\'H8\',\'tbflyer\',\'poster\',\'tb\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:652713,');
document.writeln('accountId:300559,');
document.writeln('layout:"VMMIT",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:717,');
document.writeln('mediaAreaH:300,');
document.writeln('textAreaW:717,');
document.writeln('textAreaH:281,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:0,');
document.writeln('layoutMarginRight:0,');
document.writeln('layoutMarginBottom:0,');
document.writeln('layoutMarginLeft:0,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('<div id="maMap" style="position:relative;width:545px;height:589px;overflow:hidden;margin-bottom:0px;"><script type="text/javascript">');
document.writeln('var mapViewer=new maClient.MapViewer();');
document.writeln('</script></div>');
document.writeln('<div id="maAbsBlock" style="top:0px; left:553px; width:717px;">');
document.writeln('      <div id="maHotspotMediaArea" style="margin-bottom:8px;"></div>');
document.writeln('      <div id="maTextArea" style="margin:8px 0px 0px 0px;">');
document.writeln('        <div id="maHotspotTitle">');
document.writeln('        </div>');
document.writeln('        <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
