document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:14,');
document.writeln('pageName:"Links",');
document.writeln('mapId:"datasheet5",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:0,');
document.writeln('stageH:0,');
document.writeln('mapWidth:0,');
document.writeln('mapHeight:0,');
document.writeln('mapAreaScale:NaN,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:true,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"0205_01_0011.jpg",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[],');
document.writeln('markerStyleTable:[],');
document.writeln('pageId:"35911",');
document.writeln('mapFileName:"0100_01_0000.jpg",');
document.writeln('mapInsetFileName:"_0100_01_0000.jpg",');
document.writeln('mapSwfName:"0050_14_0000.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"NaN",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'datasheet2\',\'gallery2\',\'datasheet6\',\'map4\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'students\',\'videos\',\'datasheet5\',\'0205_01_0011.jpg\',\'Links\',\'<div style="margin: 12px;" class="nlmText"> <p style="font-style: italic; margin-bottom: 24px;" class="nlmTitle">For more information on any of these topics, please visit:</p> <div class="nlmTitle">National Library of Medicine</div> <ul class="nlmLinksList">     <li><a target="_blank" title="http://www.nlm.nih.gov" href="http://www.nlm.nih.gov/">NLM home page</a></li>     <li><a target="_blank" href="http://www.nlm.nih.gov/pubs/factsheets/intlmedlars.html">NLM international programs</a></li> </ul> <div class="nlmTitle">Connecting African Malaria Researchers: MIMComNet</div> <ul class="nlmLinksList">     <li><a title="http://www.nlm.nih.gov/mimcom/mimcomhomepage.html" href="http://www.nlm.nih.gov/mimcom/mimcomhomepage.html" target="_blank">NLM Malaria Research Resources</a></li> </ul> <div class="nlmTitle">Developing a Culture of Research and Community Involvement: African Medical Students</div> <ul class="nlmLinksList">     <li><a href="http://www.nlm.nih.gov/medlineplus/africa/" title="http://www.nlm.nih.gov/medlineplus/africa/" target="_blank">MedlinePlus Tutorials for Africa</a></li>     <li><a title="http://www.youtube.com/watch?v=ez5HH8_4WOc" href="http://www.youtube.com/watch?v=ez5HH8_4WOc" target="_blank">Julia Royall, Chief, NLM International Programs, You Tube video on Malaria Tutorial part 1</a></li>     <li><a href="http://www.youtube.com/watch?v=JqZgeQvqiRU&amp;feature=relmfu" title="http://www.youtube.com/watch?v=JqZgeQvqiRU&amp;feature=relmfu" target="_blank">Julia Royall, Chief, NLM International Programs, You Tube video on Malaria Tutorial part 2</a></li> </ul> <div class="nlmTitle">Empowering African Medical Librarians: NLM Associate Fellows and Network of African Medical Librarians</div> <ul class="nlmLinksList">     <li><a href="http://karibouconnections.net/medlibafrica/" title="http://karibouconnections.net/medlibafrica/" target="_blank">Network of African Medical Librarians</a></li>     <li><a title="http://www.nlm.nih.gov/about/training/associate/internationalinfo.html" href="http://www.nlm.nih.gov/about/training/associate/internationalinfo.html" target="_blank">NLM International Associate Fellows</a></li>     <li><a href="http://karibouconnections.net/medlibafrica/#cour" target="_blank">Finding, organizing and using health information: A training manual for students, researchers and health workers in Africa</a></li> </ul> <div class="nlmTitle">Strengthening African Medical Journals: African Journal Partnership Project</div> <ul class="nlmLinksList">     <li><a title="http://ajpp-online.org" href="http://ajpp-online.org" target="_blank">African Journal Partnership Project</a></li> </ul> </div>\',\'creditsvideo\'],');
document.writeln('pageTable:[\'0,3\',\'1,4\',\'2,15\',\'3,6\',\'4,1\',\'5,7\',\'6,8\',\'7,9\',\'8,10\',\'9,13\',\'10,14\',\'14,16\'],');
document.writeln('slideTable:[\'688243,14,10,12,13,11,507,381,0,-1,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'other\',\'datasheet5\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:688243,');
document.writeln('accountId:300559,');
document.writeln('layout:"VTTII",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:507,');
document.writeln('mediaAreaH:589,');
document.writeln('textAreaW:755,');
document.writeln('textAreaH:589,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:0,');
document.writeln('layoutMarginRight:0,');
document.writeln('layoutMarginBottom:0,');
document.writeln('layoutMarginLeft:0,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)" class="current">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('    <div id="maTextArea" style="margin:0px 8px 0px 0px;">');
document.writeln('      <div id="maHotspotTitle">');
document.writeln('      </div>');
document.writeln('      <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('    </div>');
document.writeln('    <div id="maAbsBlock" style="top:0px; left:763px; width:507px; height:589px;">');
document.writeln('      <div id="maHotspotMediaArea" style="margin-bottom:0px;"></div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
