document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:13,');
document.writeln('pageName:"Videos",');
document.writeln('mapId:"videos",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:0,');
document.writeln('stageH:0,');
document.writeln('mapWidth:0,');
document.writeln('mapHeight:0,');
document.writeln('mapAreaScale:NaN,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:true,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[],');
document.writeln('markerStyleTable:[],');
document.writeln('pageId:"34023",');
document.writeln('mapFileName:"0100_01_0000.jpg",');
document.writeln('mapInsetFileName:"_0100_01_0000.jpg",');
document.writeln('mapSwfName:"0050_13_0000.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"NaN",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'datasheet2\',\'gallery2\',\'datasheet6\',\'map4\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'students\',\'videos\',\'\',\'Videos\',\'<div class="nlmText" style="margin: 12px;"> <p class="nlmTitle" style="font-style: italic; margin-bottom: 24px;">List of Videos</p> <div class="nlmTitle">What do you think of when you think of Africa?</div> <ul class="nlmLinksList">     <li><a href="./page3.htm">Africa Montage</a></li> </ul> <div class="nlmTitle nlmGreen">Developing a Culture of Research and Community Involvement: African Medical Students</div> <ul class="nlmLinksList">     <li><a href="./page6.htm?hotspot=students">COBES Medical Students 2006</a></li>     <li><a href="./page10.htm?hotspot=11">COBES Medical Students 2007</a></li>     <li><a href="./page10.htm?hotspot=9">Welcome to Mifumi Village</a></li>     <li><a href="./page10.htm?hotspot=11">Nursing Sister Goretti, Mifumi Health Center</a></li> </ul> <div class="nlmTitle nlmPurple">Connecting African Malaria Researchers: MIMComNet</div> <ul class="nlmLinksList">     <li><a href="./page6.htm?hotspot=H1">Dr. David Afori-Adjei, Rector, Ghana College of Physicians and Surgeons</a></li>     <li><a href="./page6.htm?hotspot=H1">Dr. Andrew Githeko, Chief Research Officer &amp; Head: Climate and Human Health Research Unit, Kenya Medical Research Institute</a></li> </ul> <div class="nlmTitle nlmBlue">Strengthening African Medical Journals: African Journal Partnership Project</div> <ul class="nlmLinksList">     <li><a href="./page6.htm?hotspot=H4">Dr. James Tumwine, Editor in Chief of African Health Sciences and Professor of Paediatrics and Child Health, Makerere University College of Health Sciences, Kampala, Uganda</a></li> </ul> <div class="nlmTitle nlmOrange">Empowering African Medical Librarians: NLM Associate Fellows and Network of African Medical Librarians</div> <ul class="nlmLinksList">     <li><a href="./page6.htm?hotspot=H3">Introduction from each network member</a></li>     <li><a href="./page6.htm?hotspot=H3">Christine Kanyengo, Deputy University Librarian, University of Zambia</a></li> </ul> <div class="nlmTitle">Credits</div> <ul class="nlmLinksList">     <li><a href="./page16.htm">Credits Video</a></li> </ul> </div>\',\'datasheet5\',\'creditsvideo\'],');
document.writeln('pageTable:[\'0,3\',\'1,4\',\'2,15\',\'3,6\',\'4,1\',\'5,7\',\'6,8\',\'7,9\',\'8,10\',\'9,13\',\'13,14\',\'14,16\'],');
document.writeln('slideTable:[\'661529,13,9,11,12,10,0,0,0,-1,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'other\',\'videos\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:661529,');
document.writeln('accountId:300559,');
document.writeln('layout:"HIITT",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:1270,');
document.writeln('mediaAreaH:300,');
document.writeln('textAreaW:1270,');
document.writeln('textAreaH:281,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:0,');
document.writeln('layoutMarginRight:0,');
document.writeln('layoutMarginBottom:0,');
document.writeln('layoutMarginLeft:0,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)" class="current">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('    <div id="maHotspotMediaArea" style="margin-bottom:8px;"></div>');
document.writeln('    <div id="maTextArea" style="margin:8px 0px 0px 0px;">');
document.writeln('      <div id="maHotspotTitle">');
document.writeln('      </div>');
document.writeln('      <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
