document.writeln('<script type="text/javascript">');
document.writeln('var maTour = {');
document.writeln('version:"03_0020",');
document.writeln('buildId:"1195",');
document.writeln('pageNumber:16,');
document.writeln('pageName:"Credits",');
document.writeln('mapId:"creditsvideo",');
document.writeln('blinkCount:6,');
document.writeln('visitedMarkerAlpha:100,');
document.writeln('editMode:false,');
document.writeln('stageW:0,');
document.writeln('stageH:0,');
document.writeln('mapWidth:0,');
document.writeln('mapHeight:0,');
document.writeln('mapAreaScale:NaN,');
document.writeln('runSlideShow:false,');
document.writeln('slideShowInterval:2000,');
document.writeln('mapInsetLocation:4,');
document.writeln('mapInsetSize:112,');
document.writeln('mapInsetColor:"#dbdbff",');
document.writeln('mapZoomControlColor:"#ffffff",');
document.writeln('infoPage:true,');
document.writeln('hasDirectory:false,');
document.writeln('firstImageSrc:"",');
document.writeln('marker:{');
document.writeln('viewId:0,');
document.writeln('x:0,');
document.writeln('y:0,');
document.writeln('w:0,');
document.writeln('h:0,');
document.writeln('absX:0,');
document.writeln('absY:0,');
document.writeln('rectTop:null,');
document.writeln('rectRight:null,');
document.writeln('rectBottom:null,');
document.writeln('rectLeft:null},');
document.writeln('mobileDeviceFeaturesEnabled:true,');
document.writeln('desktopDefaultIsHtml5:false,');
document.writeln('mobileDefaultIsFlash:false,');
document.writeln('selectsOnTouchStart:false,');
document.writeln('enlargeHitTestArea:false,');
document.writeln('disableBlendEffect:false,');
document.writeln('disableSmoothPanning:false,');
document.writeln('showZoomControlOnIOs:false,');
document.writeln('entirePopupVisible:false,');
document.writeln('enableImagePreloading:false,');
document.writeln('useTouchUiOnDeskop:false,');
document.writeln('markerInstanceTable:[],');
document.writeln('markerStyleTable:[],');
document.writeln('pageId:"36949",');
document.writeln('mapFileName:"0100_01_0000.jpg",');
document.writeln('mapInsetFileName:"_0100_01_0000.jpg",');
document.writeln('mapSwfName:"0050_16_0000.swf",');
document.writeln('mapZoomLevel:"0",');
document.writeln('mapZoomMidLevel:"NaN",');
document.writeln('mapPanX:"0",');
document.writeln('mapPanY:"0",');
document.writeln('mapShowZoomControl:false,');
document.writeln('stringTable:[\'datasheet2\',\'gallery2\',\'datasheet6\',\'map4\',\'map1\',\'Librarians\',\'journals\',\'researchers\',\'students\',\'videos\',\'datasheet5\',\'creditsvideo\',\'Credits\',\'<div style="margin: 60px 10px 0px 36px;"><span style="font-size: 60px; color: #8f3326;">With special thanks to ...</span></div>\',\'<iframe width="784" height="588" src="http://www.youtube.com/embed/_FnwxOqlOCw" frameborder="0" allowfullscreen></iframe>\'],');
document.writeln('pageTable:[\'0,3\',\'1,4\',\'2,15\',\'3,6\',\'4,1\',\'5,7\',\'6,8\',\'7,9\',\'8,10\',\'9,13\',\'10,14\',\'11,16\'],');
document.writeln('slideTable:[\'701844,16,11,12,13,-1,784,588,1,14,0,0,0,-1,-1,-1\'],');
document.writeln('categoryTable:[[\'other\',\'creditsvideo\']],');
document.writeln('showInstructions:false,');
document.writeln('selectedViewId:701844,');
document.writeln('accountId:300559,');
document.writeln('layout:"VTTII",');
document.writeln('canvasW:1270,');
document.writeln('canvasH:589,');
document.writeln('mediaAreaW:784,');
document.writeln('mediaAreaH:589,');
document.writeln('textAreaW:478,');
document.writeln('textAreaH:589,');
document.writeln('layoutSpacingH:8,');
document.writeln('layoutSpacingV:8,');
document.writeln('layoutMarginTop:0,');
document.writeln('layoutMarginRight:0,');
document.writeln('layoutMarginBottom:0,');
document.writeln('layoutMarginLeft:0,');
document.writeln('showSlideTitle:false,');
document.writeln('usesFixedPopup:false,');
document.writeln('usesDynamicPopup:false,');
document.writeln('usesPopup:false};');
document.writeln('</script>');
document.writeln('<div id="maTour">');
document.writeln('  <div id="maBanner"></div>');
document.writeln('  <div id="maMenuBackground">');
document.writeln('    <div id="maTopMenu">');
document.writeln('      <ul id="maTopMenuList">');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page3.htm\', null, null)">Introduction</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page4.htm\', null, null)">What do you think of when you think of Africa?</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page15.htm\', null, null)">Guiding Principles</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page6.htm\', null, null)">Engaging communities in Africa</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page1.htm\', null, null)">Project Locations</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page13.htm\', null, null)">Videos</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page14.htm\', null, null)">Links</a></li>');
document.writeln('        <li><a href="javascript:maClient.goToPage(\'page16.htm\', null, null)" class="current">Credits</a></li>');
document.writeln('      </ul>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div id="maLayout">');
document.writeln('    <div id="maTextArea" style="margin:0px 8px 0px 0px;">');
document.writeln('      <div id="maHotspotTitle">');
document.writeln('      </div>');
document.writeln('      <div id="maHotspotText" style="margin-top:0px;"></div>');
document.writeln('    </div>');
document.writeln('    <div id="maAbsBlock" style="top:0px; left:486px; width:784px; height:589px;">');
document.writeln('      <div id="maHotspotMediaArea" style="margin-bottom:0px;"></div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <noscript>');
document.writeln('    <div style="position:absolute;left:317.5px;top:147.25px;padding:8px;color:green;font-family:sans-serif;font-size:12px;background-color:#f3f3f3;border:solid 1px #777777;">');
document.writeln('This interactive map requires JavaScript');
document.writeln('</div>');
document.writeln('  </noscript>');
document.writeln('</div>');
